### 1. Import Libraries

In [ ]:
import sys
import subprocess
import warnings
warnings.filterwarnings("ignore")

try:
    import mlxtend
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "mlxtend"])

import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpgrowth, association_rules

### 2. Load Dataset

In [ ]:
orders = pd.read_csv("orders.csv")
order_items = pd.read_csv("order_items.csv")
products = pd.read_csv("products.csv")

print("Orders shape:", orders.shape)
print("Order items shape:", order_items.shape)
print("Products shape:", products.shape)

Orders shape: (33580, 10)
Order items shape: (59163, 5)
Products shape: (1197, 6)

### 3. Preview the Data

In [ ]:
orders.head()

   order_id  customer_id           order_time  ... country   device   source
0         1        13917  2025-01-31T23:07:42  ...      PL  desktop  organic
1         2         1022  2024-02-19T01:17:50  ...      FR   tablet  organic
2         3         6145  2024-12-04T20:24:13  ...      US   mobile  organic
3         4         3152  2024-07-17T08:50:47  ...      BR   mobile    email
4         5        12378  2020-08-21T16:54:16  ...      NL  desktop     paid

[5 rows x 10 columns]

In [ ]:
order_items.head()

   order_id  product_id  unit_price_usd  quantity  line_total_usd
0         1         226          107.15         1          107.15
1         2         771          116.17         1          116.17
2         3         415           94.49         1           94.49
3         3          24           42.86         1           42.86
4         4        1157           32.18         1           32.18

In [ ]:
products.head()

   product_id     category  ... cost_usd  margin_usd
0           1  Electronics  ...   352.69      217.59
1           2  Electronics  ...   263.13      235.00
2           3  Electronics  ...   309.60      238.93
3           4  Electronics  ...   153.56      114.80
4           5  Electronics  ...    42.65       21.04

[5 rows x 6 columns]

### 4. Select Needed Columns and Merge Data

In [ ]:
merged = order_items.merge(
    products[["product_id", "name"]],
    on="product_id",
    how="inner"
)

merged.head()

   order_id  product_id  ...  line_total_usd                         name
0         1         226  ...          107.15  Toaster MediumSlateBlue 575
1         2         771  ...          116.17             Socks Orange 300
2         3         415  ...           94.49        Shampoo LawnGreen 601
3         3          24  ...           42.86               SSD Orchid 272
4         4        1157  ...           32.18  Board Game DarkSeaGreen 297

[5 rows x 6 columns]

### 5. Build Transactions

In [ ]:
transactions = merged.groupby("order_id")["name"].apply(list).tolist()

print("Number of transactions:", len(transactions))
transactions[:5]

Number of transactions: 33580

[['Toaster MediumSlateBlue 575'],
 ['Socks Orange 300'],
 ['Shampoo LawnGreen 601', 'SSD Orchid 272'],
 ['Board Game DarkSeaGreen 297'],
 ['Socks GhostWhite 821', 'Jacket RosyBrown 185']]

### 6. Clean Transactions

In [ ]:
clean_transactions = []

for transaction in transactions:
    clean_transaction = []

    for item in transaction:
        item = str(item).strip()

        if item != "" and item not in clean_transaction:
            clean_transaction.append(item)

    if len(clean_transaction) > 0:
        clean_transactions.append(clean_transaction)

print("Number of clean transactions:", len(clean_transactions))
clean_transactions[:5]

Number of clean transactions: 33580

[['Toaster MediumSlateBlue 575'],
 ['Socks Orange 300'],
 ['Shampoo LawnGreen 601', 'SSD Orchid 272'],
 ['Board Game DarkSeaGreen 297'],
 ['Socks GhostWhite 821', 'Jacket RosyBrown 185']]

### 7. One-Hot Encoding

In [ ]:
te = TransactionEncoder()
te_data = te.fit(clean_transactions).transform(clean_transactions)

basket = pd.DataFrame(te_data, columns=te.columns_)

print("Basket shape:", basket.shape)
basket.head()

Basket shape: (33580, 1195)

   Action Figure BlueViolet 416  ...  Yoga Mat Tan 530
0                         False  ...             False
1                         False  ...             False
2                         False  ...             False
3                         False  ...             False
4                         False  ...             False

[5 rows x 1195 columns]